// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzFyD7gricLjDMATDasLR2MJ8_SnKYKs',
    appId: '1:315915532592:web:37999929b799af65d670f5',
    messagingSenderId: '315915532592',
    projectId: 'unisphere-b635b',
    authDomain: 'unisphere-b635b.firebaseapp.com',
    storageBucket: 'unisphere-b635b.firebasestorage.app',
    measurementId: 'G-ZJF63LFX3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDCI_mPMTSloNstopQvMcuB_v7EztbgA',
    appId: '1:315915532592:android:83d9c2197fdc0709d670f5',
    messagingSenderId: '315915532592',
    projectId: 'unisphere-b635b',
    storageBucket: 'unisphere-b635b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHyiWHaFWcG2Qfx7kb5XsquNR4DnAqPgM',
    appId: '1:315915532592:ios:b661d7ccf3e738cdd670f5',
    messagingSenderId: '315915532592',
    projectId: 'unisphere-b635b',
    storageBucket: 'unisphere-b635b.firebasestorage.app',
    iosBundleId: 'com.example.unisphereApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHyiWHaFWcG2Qfx7kb5XsquNR4DnAqPgM',
    appId: '1:315915532592:ios:b661d7ccf3e738cdd670f5',
    messagingSenderId: '315915532592',
    projectId: 'unisphere-b635b',
    storageBucket: 'unisphere-b635b.firebasestorage.app',
    iosBundleId: 'com.example.unisphereApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbGAaQ9YDe8MawqsnKr78ttYhUJLK3owc',
    appId: '1:315915532592:web:9aec1ac8507ad9e2d670f5',
    messagingSenderId: '315915532592',
    projectId: 'unisphere-b635b',
    authDomain: 'unisphere-b635b.firebaseapp.com',
    storageBucket: 'unisphere-b635b.firebasestorage.app',
    measurementId: 'G-Y1LJKLLW9D',
  );
}
