// List of all UK universities
const List<String> ukUniversities = [
  'University of Oxford',
  'University of Cambridge',
  'Imperial College London',
  'University College London',
  'London School of Economics',
  'University of Edinburgh',
  'University of Manchester',
  'University of Bristol',
  'University of Glasgow',
  'University of Birmingham',
  'University of Leeds',
  'University of Southampton',
  'University of Liverpool',
  'University of Nottingham',
  'University of Sheffield',
  'University of Warwick',
  'University of York',
  'University of Exeter',
  'University of Leicester',
  'University of Aberdeen',
  'University of St Andrews',
  'University of Bath',
  'University of Durham',
  'University of Sussex',
  'University of Reading',
  'University of Kent',
  'University of East Anglia',
  'University of Surrey',
  'University of Strathclyde',
  'University of Dundee',
  'University of Essex',
  'University of Stirling',
  'University of Plymouth',
  'University of Lancaster',
  'University of Newcastle',
  'University of Cardiff',
  'University of Queen Mary',
  'University of Roehampton',
  'University of Westminster',
  'University of Greenwich',
  'University of Hertfordshire',
  'University of Portsmouth',
  'University of Wolverhampton',
  'University of Ulster',
  'University of Central Lancashire',
  'University of Huddersfield',
  'University of Northumbria',
  'University of Lincoln',
  'University of Buckingham',
  'University of Goldsmiths',
  'University of Loughborough',
  'University of Middlesex',
  'University of Brunel',
  'University of Bournemouth',
  'University of Coventry',
  'University of De Montfort',
  'University of Anglia Ruskin',
  'University of Salford',
  'University of Swansea',
  'University of South Wales',
  'University of Aberystwyth',
  'University of Glyndwr',
  'University of Bangor',
  'University of Chester',
  'University of Edge Hill',
  'University of Keele',
  'University of Liverpool Hope',
  'University of Manchester Metropolitan',
  'University of Oxford Brookes',
  'University of Queen’s Belfast',
  'University of Sheffield Hallam',
  'University of Sunderland',
  'University of Teesside',
  'University of West of England',
  'University of Winchester',
  'University of Worcester',
  // Add more as needed
];
